<?php
/**
 * Created by PhpStorm.
 * User: Дмитрий
 * Date: 11.06.2018
 * Time: 17:57
 */
?>

<?php
/**
 * $_SESSOIN['Login'] - loginController of current user
 * If $_SESSION['Login'] = "" - no users logged in. Optional "";
 *
 * $_SESSION['register'] - if empty - user exist and cant create:
 * $_SESSION['register'] = 0 - User Already exist
 * $_SESSION['register'] = 1 - optional value
 * $_SESSION['register'] = 2 - user registration finished (All ok)
 *
 * $_SESSION['email'] - check if user put right email in field:
 * $_SESSION['email'] = 0 - Address cant be rigth. User mistake. Need re-enter email
 * $_SESSION['email'] = 1 - optional value. If user type right email this value doesn't change
 *
 * $_SESSION['password'] - check if password right:
 * $_SESSION['password'] = 0 - PASSWORD and CONFIRM PASSWORD do not match.
 * $_SESSION['password'] = -1 - Password has less than 8 symdols
 * $_SESSION['password'] = 1 - optional password value
 *
 * $_SESSION['LoginTry'] - if value equal 0 user first time enter loginController/password. If value equal 1 user already failed
 * loginController and re-enter log/pass. Optional 0;
 *
 * $userData['Login'] - user loginController
 * $userData['Password'] - user pass
 * $userData['Email'] - user Email
 * $userData['UserID'] - User ID
 * $userData['FirstName'] - User First name
 * $userData['LastName'] - User Last Name
 * $userData['Age'] - User Age
 * $userData['Admin status'] - user admin status - 0 no admin status 1 admin status
 */
?>
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>{%block title%}{% endblock %}</title>
    <link rel="stylesheet" href="../../CSS/style.css">
    <link rel="stylesheet" href="../../CSS/buttons.css">
    <link rel="stylesheet" href="../../CSS/footer.css">
    <link rel="stylesheet" href="../../CSS/gallery.css">
    <link rel="stylesheet" href="../../CSS/login.css">
    <link rel="stylesheet" href="../../CSS/profile.css">
<!--    <script src="../../js/actions.js"></script>-->
<!--    <script src="../../js/loginCheck.js"></script>-->
<!--    <script src="../../js/SignUpCheck.js"></script>-->
<!--    <script src="../../js/profile.js"></script>-->
<!--    <script src="../../js/gallery.js"></script>-->
<!--    <script src="../../js/recoverPassword.js"></script>-->
<!--    <script src="../../js/camera.js"></script>-->
<!--    <script src="../../js/ajaxclass.js"></script>-->
</head>
<body style="background-color: white">

    <a href="" ></a>

    {% block content %}{% endblock %}

</body>
</html>